### PR TITLE
12V Support Design Pull

### PR DESCRIPTION
**Pull request by kimconcillado**

### CODE REVIEW

**Comment by aaronbeekay** [comment]
#### Trace width
The traces that carry 12V current (between the relays and the screw terminals) need to be much wider in order to support 15 A current. A quick check [here](http://www.4pcb.com/trace-width-calculator.html) (1 oz^2 copper, 55º C ambient, 30º temp rise, 15 A) says you'll need a trace width of about 6.5 mm. 

These are the traces that need to be larger: 
image

If that's difficult to do, you can run traces on the top and the bottom layers simultaneously, and stitch them together with vias. You could probably run ~3.5 mm traces with that method. Or, you could add large-ish vias near each component, and solder wires onto the board to carry more current.

#### Sense resistor
The sense resistor (R1) won't do anything as drawn. It needs to be in series with the 12V current, between K2 and K3 as the circuit is drawn currently.

#### Board layout
image

U$6 should be at the edge of the board unless you have a good reason for it not to be.

@Victorb101 -- is this layout OK with what you expect?

#### Schematic, etc
* Please name your connectors X1, X2, etc -- I know the library is bad with its default symbol.
* Pin 2 of U$4 (the output screw terminal) is not connected, should be connected to GND (with a thick trace).
* I assume you know that U$5 and U$6 should be connected to the rest of their signals.

**Comment by Victorb101** [comment]
Aaron and Kim,

Just a few more thoughts to add to Aarons feedback.

-The connectors should actually be named to match the ones in the wiring
diagrams, X-125, X-134, etc. Those are made up, but you get the point. If
they don't have a name yet, give them a name and add to RW-3 Connector
Master List. Be sure to label these names on the board with silk screen.

-I'm confused what's up with the Microfit connectors. One is not connected.
But I assume it is for 12V on? The other could be decreased in size if it
only has a single signal.

-The screw terminals can be side by side if this helps decrease size.

-If you run traces along top and bottom, make sure the lengths are roughly
the same size. It would also be nice to have a large decoupling cap because
the high number of vias between the two layers can couple in a lot of
noise. Also if running larger traces is difficult in some places you can
add wire jumpers. These should have their own silkscreen labels, and
specified wire size.

Let me know if you need help with any of this. Thanks!

Victor

**Comment by kimconcillado** [comment]
@aaronbeekay not sure how to run traces on top and bottom to half width. This is it at 6.5mm. 
image

More to come.

**Comment by aaronbeekay** [comment]
@kimconcillado -- here's an example of running traces on the top and the bottom stitched with vias:

image

The vias are made with `via 'GND'`, or `via 'your_signal_name'`, or whatever.

For big traces like that, it often works better to use polygons (because the trace ends will overlap things, like you see in your screenshot). Here's an example of how I might route that trace using a polygon:

image

Polygons don't have an easy way to control overall width, so you'd just have to make sure that your polygon never gets much less than 6.5 mm wide.

It may make your life a lot easier to rearrange the relays and components on your board so that you don't have to run the big traces very far.

**Comment by kimconcillado** [comment]
U$5 and U$6 have been changed to X4 and X5 respectively, but I don't know where they connect to. 

K3 has two unconnected parts. I know one goes to 12V on but I don't know what to do besides leave a signal there. The other looks likes it's supposed to be left alone - is this correct?

**Comment by aaronbeekay** [comment]
@kimconcillado Actually, Victor is right - those parts should be named according to their names in the [rear enclosure wiring diagram](https://github.com/BuckeyeCurrent/Vehicle-wiring-diagrams/blob/master/Rear%20Enclosure/Rear%20Enclosure%20Diagram.pdf?raw=true). The 12V Support and its associated connectors are on page 2.

From that document you can see that there are three connectors expected on the 12V Support: X-342, X-350, and X-335:

image

X-335 is the connector that goes to the Magic CAN Node. It should have +3V3, GND, and the output signal from the current sense circuit.

X-342 is the +12V_ON switch. The switch goes between +12V_CONST (the output of the first relay) and +12V_ON, so the connector should have both of those signals.

It looks like X-350 is specified to provide +12V_CONST to the BeagleBone. @Victorb101 - it seems like X-350 is redundant, because that signal is already present on X-342. Can we delete X-350?

You are correct that the NC terminal on K3 should be left disconnected.

**Comment by Victorb101** [comment]
Actually yea, I think we can eliminate X-350. The schematic attached to the
earlier email didn't have this wired to anything, so how did you plan to
wire the 12V on switch? For that to work you would need to run 12v const to
the switch and the return from the switch would connect to the coil of the
12V on relay. Is this represented in the current schematic?

Victor

**Comment by aaronbeekay** [comment]
Comments on your latest commit, per your request:

* Your components will look more even if they are on a more consistent grid. For the screw terminals, relays, etc., I would suggest an 0.5 mm or 1 mm grid.
* The layout looks fine. Proof is in the routing.

**Comment by kimconcillado** [comment]
@aaronbeekay 
image

this trace isn't finished but does that mean it still works?

**Comment by aaronbeekay** [comment]
@kimconcillado - it will bitch about it until you close out that last part. You can click it and make a very short trace that doesn't go anywhere, and it will be happy.

**Comment by kimconcillado** [comment]
image
@aaronbeekay @Victorb101 halp. The remaining airwires all need to be 3.5mm traces or polygons and I'm stuck

**Comment by kimconcillado** [comment]
I lied 12V ON can be a smaller trace

**Comment by kimconcillado** [comment]
image
image
image

**Comment by aaronbeekay** [comment]
@kimconcillado - those clearance and overlap errors are happening because your vias belong to a different signal than the traces that they're stitching together. You can use the NAME command (like `name 'N$7'` to change the vias to match the other traces.

I don't get the drill size errors when I run a DRC. Make sure that you're using the "OSH Park 2-layer.dru" file when you run your DRC.

**Comment by aaronbeekay** [comment]
Other than that, board looks pretty good. Other outstanding things:

* schematic needs title block filled out
* silkscreen labels: you should label all connectors with connector name + number (e.g., X342 12V ON). Screw terminals should have polarity (+ –) labeled prominently.
* Mounting holes! Please use mounting holes for M2 or M4 size screws.
* You named X335 "LDO" - what does that mean?

**Comment by kimconcillado** [comment]
LDO comes from this picture
cam00905
a quick google search tells me its a low drop out regulator

**Comment by aaronbeekay** [comment]
@kimconcillado - the board will usually look more cluttered in the layout editor, because the tDocu, tNames, and tValues layers are turned on (these don't get printed on the PCB). If you want to see what the board will look like when it's manufactured, you can turn off tDocu/bDocu, tNames/bNames, and tValues/bValues.

The LDO in the picture isn't actually a part of the circuit anymore -- that was a power supply that we realized we didn't need. That connector carries the current measurement signal that goes to the Magic CAN Node. I think an appropriate name would be "CURRENT SENSE" or similar.

**Comment by aaronbeekay** [comment]
P.S. - in your latest commit, your mounting hole drills are much too small.

For M2 screws, you can use a ⌀2.2 drill, with ⌀4 clearance around the hole. Or for M4 screws, you can use a ⌀4.4 drill, with ⌀8 clearance.

**Comment by aaronbeekay** [comment]
Looking good. Still need:

* [ ] schematic title block filled out
* [ ] revision (v2.0) on PCB
* [ ] BOM, Gerbers, PDFs
* [ ] [Pull request for Panasonic.lbr](https://github.com/BuckeyeCurrent/Component-libraries/pull/66) completed and merged

**Comment by kimconcillado** [comment]
image
@aaronbeekay WHAT IS THIS

**Comment by kimconcillado** [comment]
@aaronbeekay I updated the library for the board and ran into these issues. I was expecting bigger issues and I am confused. These seem like small fixes - I probably need the JSM component double checked (look at the Panasonic libe)
image

**Comment by aaronbeekay** [comment]
@kimconcillado Looks great. Merged.

I updated your schematic to fill an entire 8.5x11 page, and I also updated your brd/Gerbers to fix a bug in the DRC file (not your fault).

**Pull request merged**
